apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: dependant
  annotations:
    config.kubernetes.io/depends-on: /namespaces/default/ConfigMap/marker
data:
  dependant-on-other: "true"
