apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: dependant
  annotations:
    # the "other" configmap doesnt exist in this repo, it is added by other means
    config.kubernetes.io/depends-on: /namespaces/default/ConfigMap/other
data:
  dependant-on-other: "true"
