applySpecVersion: 1
spec:
  configSync:
    enabled: true
    policyDir: .
    secretType: none
    sourceFormat: unstructured
    syncBranch: kubevirt-acm
    syncRepo: https://github.com/GoogleCloudPlatform/acm-essentials.git
    syncWait: 15
  policyController:
    enabled: true
    referentialRulesEnabled: true
    templateLibraryInstalled: true
