applySpecVersion: 1
spec:
  configSync:
    enabled: true
    policyDir: config-root
    secretType: none
    sourceFormat: unstructured
    syncBranch: kubevirt-acm
    syncRepo: https://github.com/linde/acm-minimal.git
    syncWait: 15
  policyController:
    enabled: true
    referentialRulesEnabled: true
    templateLibraryInstalled: true
