apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: acm-minimal
  git:
    secretType: ssh
    syncRepo: git@github.com:linde/acm-minimal.git
    syncBranch: acm-g8r
    policyDir: config-root
  policyController:
    enabled: true
    templateLibraryInstalled: false
    
