apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiocontrolplanes.install.istio.io
spec:
  group: install.istio.io
  names:
    kind: IstioControlPlane
    listKind: IstioControlPlaneList
    plural: istiocontrolplanes
    shortNames:
    - icp
    singular: istiocontrolplane
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
          description: >-
            APIVersion defines the versioned schema of this representation of an
            object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info:
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources
        kind:
          type: string
          description: >-
            Kind is a string value representing the REST resource this object
            represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info:
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds
        spec:
          type: object
          description: >-
            Specification of the desired state of the istio control plane
            resource. More info:
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
        status:
          type: object
          description: >-
            Status describes each of istio control plane component status at the
            current time. 0 means NONE, 1 means UPDATING, 2 means HEALTHY, 3
            means ERROR, 4 means RECONCILING. More info:
            https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/v1alpha2.pb.html
            &
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
  versions:
  - name: v1alpha2
    served: true
    storage: true
