apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: mco-root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/linde/acm-minimal.git
    branch: mco
    auth: none
    dir: config-root
