apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces: [
        "kube-system", 
        "config-management-system", 
        "config-management-monitoring", 
        "gatekeeper-system"
      ]
      processes: ["audit"]
      